spring:
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
  cache:
    type: redis
    redis:
      time-to-live: 600000
  data:
    mongodb:
      uri: ${MONGO_DB_URI:mongodb://root:root@localhost}
      database: ${MONGODB_DATABASE:chatDb}

app:
  auth:
    jwks-url: "your value from auth0"
